repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      name: black
      language: system
      entry: black xapian_backend.py
      types: [python]
      language_version: python3.7
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.1.0
  hooks:
    - id: pylint
      name: pylint
      language: system
      entry: pylint xapian_backend.py
      types: [python]
- repo: https://github.com/PyCQA/flake8
  rev: 3.7.7
  hooks:
    - id: flake8
      name: flake8
      language: system
      entry: flake8 xapian_backend.py
      types: [python]
