[tool.black]
line-length = 119
skip-string-normalization = true
target-version = ['py35']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.venv.deploy
    | _build
    | buck-out
    | build
    | dist
  )/
  | settings.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
